language: ruby

rvm:
- 2.1

cache:
- bundler

gemfile: travisGemfile

install:
- bundle install

before_script:
- chmod +x deploy.sh
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials

script: "./deploy.sh"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - HTML_FOLDER="./_site/"
  - GH_REF="jekyll-brasil/jekyll-brasil.github.io"
  - secure: ED28zVexrGl7DGMkZ1HSYsD8Jzx4j+n7feQgYmihw1SAdsXNBlmvdRDs24vBqskFsEapqyd3JpaomYO214booccUnHpmGullGhq5qmTHOdmzp2jV5w/X8j+kMN0YZzoe3RB09cIYDj4uc2gRobLsvwvmOzdKQLzHdlTEW0x/AeA9h+6CzLAWkz5zLPSiVXbJa1MgYAKIq2ACJjR5PYHIsU79rRk3aRG95Pm6bBewzODjlfEbfNwuVwOOXEIGenv6SaUGj1ucdfqySM5lPAgjbr/rZb9q6ric275bIYsVnO7qoqPu88xhwHF2lcO2ynh+lXaRhB/ZS90f6GMYLAvJBEmHLqeOdDPFGHEQMJlHGfvdskr8BcwYXQ97gtAQfjvXpgdAl9/6Am/31xVygFiDqBhED5mpqyyQK4nEADshDutYxYSiF1pw78WVFK4xc3iFpVcCfA8cyXo/7U5j3Bms5SB82RZNZDly2zbIUot+ECViro1euJFiv7QMmWDMmpmaj+ltfNtwxZJBe3ORM2xgSYxcB3osSgnclNaork3JAqLKfZWnodB99tEBKyio6o147UVxy+5Kkf9nd/9WCx5arwtuk/a/0aUpKZyqhKMSs9b+YEPHC/lSU0Dlv3zfKztGeOYZkX62tPn9C8jx708Eeg0bkRJe5WWZTiAXqchXAFg=

branches:
  only:
  - master
  - source

notifications:
  email: true
